name: Tests

# Déclencher les tests à chaque push et pull request
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Définir des jobs qui tournent en parallèle
jobs:
  # ==========================================
  # JOB 1 : Tests Python
  # ==========================================
  test-python:
    name: Tests Python et Dépendances
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Cache pip pour accélérer
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Installer les dépendances
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Vérifier l'import de chaque module
      - name: Test imports des modules Python
        run: |
          echo "🔍 Test des imports..."
          python -c "import numpy; print('✅ NumPy OK')"
          python -c "import pyvista; print('✅ PyVista OK')"
          python -c "import vtk; print('✅ VTK OK')"
          python -c "import trimesh; print('✅ Trimesh OK')"
          python -c "import ezdxf; print('✅ ezdxf OK')"
          python -c "import svgwrite; print('✅ svgwrite OK')"
          python -c "import scipy; print('✅ SciPy OK')"
          python -c "import PIL; print('✅ Pillow OK')"
          python -c "import networkx; print('✅ NetworkX OK')"
          python -c "import svgpathtools; print('✅ svgpathtools OK')"
          echo "✅ Tous les modules s'importent correctement !"

      # 6. Vérifier la syntaxe de procedure.py
      - name: Check syntax procedure.py
        run: |
          echo "🔍 Vérification de la syntaxe Python..."
          python -m py_compile procedure.py
          echo "✅ Syntaxe Python correcte !"

      # 7. Test basique : créer un meuble simple
      - name: Test création meuble simple
        run: |
          echo "🧪 Test de génération d'un meuble basique..."
          # Test avec un meuble simple
          python procedure.py "M1(1000,400,1000)E" || echo "⚠️ Test meuble simple échoué"
          
          # Vérifier que les fichiers GLB sont créés
          if [ -f "meuble.glb" ]; then
            echo "✅ meuble.glb créé avec succès"
          else
            echo "❌ meuble.glb non créé"
            exit 1
          fi

  # ==========================================
  # JOB 2 : Tests PHP
  # ==========================================
  test-php:
    name: Tests PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer PHP 8.2
      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json, fileinfo

      # Vérifier la syntaxe de tous les fichiers PHP
      - name: Check PHP syntax
        run: |
          echo "🔍 Vérification de la syntaxe PHP..."
          FILES_CHECKED=0
          ERRORS=0
          
          for file in *.php; do
            if [ -f "$file" ]; then
              echo "  Vérification de $file..."
              if php -l "$file" > /dev/null 2>&1; then
                echo "  ✅ $file OK"
              else
                echo "  ❌ $file ERREUR"
                php -l "$file"
                ERRORS=$((ERRORS + 1))
              fi
              FILES_CHECKED=$((FILES_CHECKED + 1))
            fi
          done
          
          echo ""
          echo "📊 Résultat : $FILES_CHECKED fichiers vérifiés"
          
          if [ $ERRORS -gt 0 ]; then
            echo "❌ $ERRORS fichier(s) avec erreurs"
            exit 1
          else
            echo "✅ Tous les fichiers PHP sont valides !"
          fi

      # Test des fichiers JSON
      - name: Validate JSON files
        run: |
          echo "🔍 Validation des fichiers JSON..."
          
          # Tester devis.json
          if [ -f "devis.json" ]; then
            if python -m json.tool devis.json > /dev/null 2>&1; then
              echo "✅ devis.json valide"
            else
              echo "❌ devis.json invalide"
              exit 1
            fi
          fi
          
          # Tester produit.json
          if [ -f "produit.json" ]; then
            if python -m json.tool produit.json > /dev/null 2>&1; then
              echo "✅ produit.json valide"
            else
              echo "❌ produit.json invalide"
              exit 1
            fi
          fi

  # ==========================================
  # JOB 3 : Vérification de la structure
  # ==========================================
  test-structure:
    name: Vérifier la structure du projet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required files and folders
        run: |
          echo "🔍 Vérification de la structure du projet..."
          ERRORS=0
          
          # Fichiers essentiels
          echo ""
          echo "📄 Vérification des fichiers essentiels..."
          for file in "procedure.py" "requirements.txt" "00.php" "01.php" "02.php" "03.php" ".gitignore"; do
            if [ -f "$file" ]; then
              echo "  ✅ $file existe"
            else
              echo "  ❌ $file manquant"
              ERRORS=$((ERRORS + 1))
            fi
          done
          
          # Dossiers essentiels
          echo ""
          echo "📁 Vérification des dossiers essentiels..."
          for dir in "crm" "devis" "pieces" "uploads" "textures"; do
            if [ -d "$dir" ]; then
              echo "  ✅ dossier $dir existe"
            else
              echo "  ❌ dossier $dir manquant"
              ERRORS=$((ERRORS + 1))
            fi
          done
          
          echo ""
          if [ $ERRORS -gt 0 ]; then
            echo "❌ $ERRORS élément(s) manquant(s)"
            exit 1
          else
            echo "✅ Structure du projet correcte !"
          fi

  # ==========================================
  # JOB 4 : Tests d'intégration
  # ==========================================
  test-integration:
    name: Tests d'intégration
    runs-on: ubuntu-latest
    needs: [test-python, test-php]  # Attend que les tests de base passent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test workflow complet
        run: |
          echo "🧪 Test du workflow complet..."
          
          # 1. Générer un meuble
          echo "1️⃣ Génération du meuble..."
          python procedure.py "M1(800,400,600)EF" || exit 1
          
          # 2. Vérifier les outputs
          echo "2️⃣ Vérification des outputs..."
          
          # GLB files
          for file in "meuble.glb" "meublep.glb" "meublen.glb" "meublenp.glb"; do
            if [ -f "$file" ]; then
              SIZE=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
              if [ "$SIZE" -gt 1000 ]; then
                echo "  ✅ $file créé ($SIZE bytes)"
              else
                echo "  ⚠️ $file trop petit ($SIZE bytes)"
              fi
            else
              echo "  ❌ $file non créé"
              exit 1
            fi
          done
          
          # DXF/SVG files
          if [ -f "pieces/piece_general.dxf" ]; then
            echo "  ✅ DXF créé"
          else
            echo "  ❌ DXF non créé"
            exit 1
          fi
          
          if [ -f "pieces/piece_general.svg" ]; then
            echo "  ✅ SVG créé"
          else
            echo "  ❌ SVG non créé"
            exit 1
          fi
          
          # JSON output
          if [ -f "produit.json" ]; then
            echo "  ✅ produit.json créé"
            # Vérifier que le prix est calculé
            if grep -q '"prixht"' produit.json; then
              echo "  ✅ Prix calculé"
            else
              echo "  ❌ Prix non calculé"
              exit 1
            fi
          fi
          
          echo "✅ Workflow complet OK !"

  # ==========================================
  # Résumé final
  # ==========================================
  summary:
    name: Résumé des tests
    runs-on: ubuntu-latest
    needs: [test-python, test-php, test-structure, test-integration]
    if: always()

    steps:
      - name: Test Summary
        run: |
          echo "📊 RÉSUMÉ DES TESTS CI/CD"
          echo "================================"
          echo ""
          echo "✅ Tests Python : ${{ needs.test-python.result }}"
          echo "✅ Tests PHP : ${{ needs.test-php.result }}"
          echo "✅ Structure : ${{ needs.test-structure.result }}"
          echo "✅ Intégration : ${{ needs.test-integration.result }}"
          echo ""
          echo "================================"






